### ISSUE TITLE
Oculus Quest2 thumb cause random movement

### ISSUE THREAD

**Issue by nightgryphon** [jure/aframe-blink-controls#26]
Pulling controller thumb not enough straight forward or backwards cause unexpected very fast movement in some unexpected direction

**Comment by vincentfretin** [comment]
I had an issue with fast turning when pressing fully the joystick, that was when I had the `movement-controls` (with the default `controls:gamepad,keyboard,touch`) enabled at the same time. If you use `movement-controls`, be sure to disable it when you are in VR by setting `enabled:false` or by listing the controls you want explicitly and removing gamepad controls from the list, for example `movement-controls="controls:keyboard"`
If that's not it, please provide a reproducible example where you have the issue.

**Comment by nightgryphon** [comment]
Oh. It was not exactly the case but gives me an idea. I've forgot to turn off the previously used custom module which also handle movement/snap turn functionality. Together they produced very unexpected effects in some cases. Thanks!
