### ISSUE TITLE
how to use aframe blink controls to navigate in the VR scene?

### ISSUE THREAD

**Issue by addy1997** [jure/aframe-blink-controls#28]
Hi @jure,

With the hand-tracking controls alone I am not able to navigate in the VR scene. On Discord, I was advised to use the blink controls for locomotion in the VR scene. I want to configure the blink controls to start after the I pinch my fingers so that I can navigate the VR scene.

Here's the link to my code: https://jsfiddle.net/adwait3301/qov10s29/777/

Could you please recommend anything?

**Comment by vincentfretin** [comment]
Hi,

The only events of `hand-tracking-controls` are related to the pinch gesture:
https://aframe.io/docs/master/components/hand-tracking-controls.html#events

Did you try
`blink-controls="snapTurn:false;startEvents:pinchstarted;endEvents:pinchended"` ?

There is no equivalent for the `cancelEvents` though like we use for `handy-controls` point gesture:
`blink-controls="snapTurn:false;startEvents:pose_point_fuseShort;endEvents:pose_point_fuseLong;cancelEvents:pose_cancel_point;"`

**Comment by addy1997** [comment]
Yeah, I tried this but it works partially. The code snippet can be found below:


```
<a-entity id="leftHand" hand-tracking-controls="hand: left; modelColor: #ADD8E6; modelStyle: mesh" blink-controls="snapTurn:false; startEvents:pinchstarted; endEvents:pinchended; cameraRig: #camera-control; teleportOrigin: #camera-head; curveHitColor: #99ff99; curveMissColor: #ff0000; curveNumberPoints: 15; curveLineWidth: 0.05; curveShootingSpeed: 5; defaultPlaneSize: 100; landingMaxAngle: 45;"></a-entity>`
```
```
<a-entity id="rightHand" hand-tracking-controls="hand: right; modelColor: #ADD8E6; modelStyle: mesh" blink-controls="snapTurn:false; startEvents:pinchstarted; endEvents:pinchended; cameraRig: #camera-control; teleportOrigin: #camera-head; curveHitColor: #99ff99; curveMissColor: #ff0000; curveNumberPoints: 15; curveLineWidth: 0.05; curveShootingSpeed: 5; defaultPlaneSize: 100; landingMaxAngle: 45;"></a-entity>
```
